[[domains]]
domain = "http://localhost:3000"
enable_session_management = true
enable_preflight_simulation = false

## Tx Variation 0
[[domains.tx_variations]]
version = "v0"
name = "Sample v1 Variation"
whitelisted_programs = [
    "4C6oWAqFgu2TSjVA7Z4u4SK3uqMmnJjgoNCHwuU3BJVX",
]



## Tx Variation 1
[[domains.tx_variations]]
version = "v1"
name = "Example v1 Variation"
max_gas_spend = 1000000

# Instruction 0
[[domains.tx_variations.instructions]]
program = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
required = false

# Instruction 1
[[domains.tx_variations.instructions]]
program = "Examtz9qAwhxcADNFodNA2QpxK7SM9bCHyiaUvWvFBM3"
required = true

[[domains]]
domain = "sessions"
enable_session_management = true
enable_preflight_simulation = false

[[domains.tx_variations]]
version = "v1"
name = "Intent Transfer"
max_gas_spend = 10000

[[domains.tx_variations.instructions]]
program = "Ed25519SigVerify111111111111111111111111111"
required = true

# numSignatures = 1
[[domains.tx_variations.instructions.data]]
start_byte = 0
data_type = "U8"
constraint = { EqualTo = [ {U8 = 1} ] }

# padding = 0
[[domains.tx_variations.instructions.data]]
start_byte = 1
data_type = "U8"
constraint = { EqualTo = [ {U8 = 0} ] }

# signatureOffset = 16 + 32 = 48
[[domains.tx_variations.instructions.data]]
start_byte = 2
data_type = "U16"
constraint = { EqualTo = [ {U16 = 48} ] }

# signatureInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 4
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

# publicKeyOffset = 16
[[domains.tx_variations.instructions.data]]
start_byte = 6
data_type = "U16"
constraint = { EqualTo = [ {U16 = 16} ] }

# publicKeyInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 8
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

# messageOffset = 16 + 32 + 64 = 112
[[domains.tx_variations.instructions.data]]
start_byte = 10
data_type = "U16"
constraint = { EqualTo = [ {U16 = 112} ] }

# messageInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 14
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

[[domains.tx_variations.instructions]]
program = "Xfry4dW9m42ncAqm8LyEnyS5V6xu5DSJTMRQLiGkARD"
required = true

# instruction = 0 (SendTokens)
[[domains.tx_variations.instructions.data]]
start_byte = 0
data_type = "U8"
constraint = { EqualTo = [ {U8 = 0} ] }



[[domains.tx_variations]]
version = "v1"
name = "Intent NTT Bridge"
max_gas_spend = 15000

[[domains.tx_variations.instructions]]
program = "Ed25519SigVerify111111111111111111111111111"
required = true

# numSignatures = 1
[[domains.tx_variations.instructions.data]]
start_byte = 0
data_type = "U8"
constraint = { EqualTo = [ {U8 = 1} ] }

# padding = 0
[[domains.tx_variations.instructions.data]]
start_byte = 1
data_type = "U8"
constraint = { EqualTo = [ {U8 = 0} ] }

# signatureOffset = 16 + 32 = 48
[[domains.tx_variations.instructions.data]]
start_byte = 2
data_type = "U16"
constraint = { EqualTo = [ {U16 = 48} ] }

# signatureInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 4
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

# publicKeyOffset = 16
[[domains.tx_variations.instructions.data]]
start_byte = 6
data_type = "U16"
constraint = { EqualTo = [ {U16 = 16} ] }

# publicKeyInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 8
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

# messageOffset = 16 + 32 + 64 = 112
[[domains.tx_variations.instructions.data]]
start_byte = 10
data_type = "U16"
constraint = { EqualTo = [ {U16 = 112} ] }

# messageInstructionIndex = 0xffff
[[domains.tx_variations.instructions.data]]
start_byte = 14
data_type = "U16"
constraint = { EqualTo = [ {U16 = 0xffff} ] }

[[domains.tx_variations.instructions]]
program = "Xfry4dW9m42ncAqm8LyEnyS5V6xu5DSJTMRQLiGkARD"
required = true

# instruction = 1 (BridgeNttTokens)
[[domains.tx_variations.instructions.data]]
start_byte = 0
data_type = "U8"
constraint = { EqualTo = [ {U8 = 1} ] }

[[domains.tx_variations.instructions.data]]
start_byte = 1
data_type = "NttSignedQuote"
constraint = { EqualTo = [ {NttSignedQuoter = "0x5241c9276698439fef2780dbab76fec90b633fbd"} ] }