keypair_path = "./tilt/keypairs/sponsor.json"
solana_url = "http://127.0.0.1:8899"
listen_address = "0.0.0.0:4000"
max_sponsor_spending = 0.005
program_whitelist = [
    "Examtz9qAwhxcADNFodNA2QpxK7SM9bCHyiaUvWvFBM3",
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
    "Ed25519SigVerify111111111111111111111111111",
    "SesswvJ7puvAgpyqp7N8HnjNnvpnS8447tKNF3sPgbC"
]
