[external]
paymaster_endpoint = "http://localhost:4000"
rpc_url = "http://localhost:8899"
domain = "http://localhost:3000"

[validity]
valid_rate = 0.80
invalid_signature_rate = 0.05
invalid_constraint_rate = 0.05
invalid_fee_payer_rate = 0.05
invalid_gas_rate = 0.05
