[external]
paymaster_endpoint = "https://paymaster.dourolabs.app"
rpc_url = "https://mainnet.fogo.io"
domain = "https://sessions-example.fogo.io"

[validity]
valid_session_creation_rate = 0
valid_memo_rate = 1
invalid_signature_rate = 0
invalid_constraint_rate = 0
invalid_fee_payer_rate = 0
invalid_gas_rate = 0
