[external]
paymaster_endpoint = "https://paymaster.dourolabs.app"
rpc_url = "https://mainnet.fogo.io"
domain = "https://sessions-example.fogo.io"
chain_id = "fogo-mainnet"

[validity]
valid_rate = 1
invalid_signature_rate = 0
invalid_constraint_rate = 0
invalid_fee_payer_rate = 0
invalid_gas_rate = 0
