[package]
name = "solana-intents"
description = "A set of utilities for loading & validating intent-based transactions in solana"
edition = { workspace = true }
license = { workspace = true }
repository = "https://github.com/fogo-foundation/fogo-sessions"
version = "0.1.1"

[lib]
crate-type = ["rlib"]
name = "solana_intents"

[dependencies]
borsh = { workspace = true }
itertools.workspace = true
nom = { workspace = true }
solana-offchain-message = { workspace = true }
solana-program = { workspace = true }

[lints]
workspace = true
