on:
  push:
    branches: [main, ci/unified-changesets]  # Added test branch
name: Create Release PR (Knope)
jobs:
  prepare-release:
    permissions:
      contents: write
      pull-requests: write
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')" # Skip merges from releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FOGO_SESSIONS_KNOPE_RELEASE_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name GitHub Actions
          git config user.email github-actions@github.com
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.6
      - name: test
        run: |
          git switch -c release
          git commit -m 'test commit' --allow-empty
          git push --set-upstream origin release
      - run: knope prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.FOGO_SESSIONS_KNOPE_RELEASE_TOKEN }}