on:
  push:
    branches: [main, ci/unified-changesets]
name: Create Release PR (Knope)
jobs:
  prepare-release:
    permissions:
      contents: write
      pull-requests: write
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')" # Skip merges from releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.6
      - run: knope prepare-release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
